import { PERMISSIONS } from "../constants/permissions";

export default [

  PERMISSIONS.VIEW_USERS,

  PERMISSIONS.CREATE_USERS,

  PERMISSIONS.EDIT_USERS,

  PERMISSIONS.DELETE_USERS,

  PERMISSIONS.VIEW_DONATIONS,

  PERMISSIONS.MANAGE_COURSES,

  PERMISSIONS.MANAGE_EVENTS,

  PERMISSIONS.MANAGE_BLOGS,

  PERMISSIONS.MANAGE_CAMPAIGNS

];